# ANNEX: C
# PREDICTION CODE FOR US COVID 19 CASES USING NEURAL NETWORKS
## SUBMITTED BY: FAISAL JAVED
### MACHINE LEARNING PROJECT_2 (MS RIME 2020)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## DATA SET DETAILS 
### GATHERING & CLEANING

In [2]:
Data = pd.read_excel("USA Statewise Covid Data.xlsx")   #importing Data from excell file
Data.head()

,Date,Xo,Date_Code,States_Code,Temperatures,Humidity,LandArea,Population_Density,Cases_per_day
0,2020-12-06,1,0,1,11.6,77.1,570641,1.2863,757
1,2020-12-06,1,0,2,46.6,71.6,50645,96.9221,2288
2,2020-12-06,1,0,3,41.3,70.9,52035,58.403,1542
3,2020-12-06,1,0,4,38.0,80.0,77,716,0
4,2020-12-06,1,0,5,43.6,38.5,113594,64.9549,5376

In [3]:
X = Data.drop(['Date','Cases_per_day','LandArea','Xo'],1)

In [4]:
X['Population_Density']= X['Population_Density'].astype(float)

### SCALING OF DATA

In [5]:
x = X/(X.max(axis=0) + np.spacing(0))

In [6]:
x.shape

(14840, 5)

### SPLITTING OF DATA SET INTO TRAIN,TEST & VALID DATA

In [7]:
data_train = round(0.6*len(Data))
data_valid = round(data_train+0.2*len(Data))

In [8]:
train_x = x[:data_train]
valid_x = x[data_train:data_valid]
test_x = x[data_valid:]

In [9]:
train_x = train_x.T
train_x.shape

(5, 8904)

In [10]:
valid_x = valid_x.T
valid_x.shape

(5, 2968)

In [11]:
test_x = test_x.T
test_x.shape

(5, 2968)

In [12]:
Y = Data['Cases_per_day']

In [13]:
train_y = Y[:data_train]
valid_y = Y[data_train:data_valid]
test_y = Y[data_valid:]

In [14]:
train_y = train_y.values.reshape(1,train_x.shape[1]) #Reshaping of y coloumn for ease of mathematical multiplication
train_y.shape

(1, 8904)

In [15]:
valid_y = valid_y.values.reshape(1,valid_x.shape[1])
valid_y.shape

(1, 2968)

In [16]:
test_y = test_y.values.reshape(1,test_x.shape[1])
test_y.shape

(1, 2968)

### USING PARAMETERS FROM TRAINING MODEL:

In [17]:
W1 = ([[ 0.1005317 ,  0.22764016,  0.30283889,  0.41307084, -0.00878571],
        [ 0.10726795,  0.25702785,  0.34551263,  0.42787668,  0.00089543],
        [ 0.14617458,  0.32950514,  0.43602154,  0.52256502,  0.01736305],
        [ 0.11533403,  0.26414214,  0.38688043,  0.45229581,  0.01045548],
        [ 0.20062603,  0.45484786,  0.65046201,  0.78392557,  0.01454719],
        [ 0.15400612,  0.33459909,  0.4722262 ,  0.5788094 ,  0.01185078],
        [ 0.18565756,  0.4327009 ,  0.55887736,  0.71523139,  0.01976579],
        [ 0.16175869,  0.32835734,  0.45076296,  0.56240652,  0.01804493],
        [ 0.11018652,  0.2546402 ,  0.33221024,  0.44669934,  0.02419948],
        [ 0.14727005,  0.33440278,  0.46662971,  0.5628373 ,  0.01374376],
        [ 0.14364158,  0.28786791,  0.41031109,  0.50644076,  0.01572308],
        [ 0.10829913,  0.20230712,  0.30114344,  0.36487727, -0.01019915],
        [ 0.13168729,  0.29487298,  0.42008656,  0.5183047 , -0.00856066],
        [ 0.18271912,  0.3907151 ,  0.54996245,  0.69632152,  0.02285575],
        [ 0.07096658,  0.17716009,  0.23590965,  0.29426549, -0.0042446 ],
        [ 0.05748074,  0.06487184,  0.12852868,  0.16542658, -0.01653239]]),
b1 = ([[0.47823922],
        [0.52823491],
        [0.64305632],
        [0.55396629],
        [0.95647949],
        [0.71445121],
        [0.86057077],
        [0.67774723],
        [0.51768132],
        [0.6881468 ],
        [0.61119131],
        [0.43713264],
        [0.62071621],
        [0.8328784 ],
        [0.35382257],
        [0.19106971]]),
W2 = ([[10.54688957, 10.47303148, 10.59026428, 10.58699344, 10.51445713,
         10.42621253, 10.54952942, 10.57823338, 10.58692647, 10.54623335,
         10.55588064, 10.59507172, 10.57080311, 10.53995594, 10.54373333,
         10.55177346],
        [10.53364139, 10.45290026, 10.57477256, 10.5325564 , 10.51111239,
         10.42503485, 10.50594697, 10.551563  , 10.56953056, 10.5494587 ,
         10.55136733, 10.57487553, 10.54275607, 10.5014423 , 10.53879663,
         10.51707389],
        [10.42048072, 10.34943957, 10.45964123, 10.44988934, 10.39252721,
         10.31259004, 10.44201389, 10.43206711, 10.4615516 , 10.42774783,
         10.42950789, 10.47384266, 10.45710055, 10.41943034, 10.44885552,
         10.41237765],
        [10.31588155, 10.21422961, 10.33636146, 10.32529084, 10.26482057,
         10.20442527, 10.29064749, 10.33202999, 10.33200289, 10.30742725,
         10.31310781, 10.34593631, 10.31044794, 10.28024383, 10.30149166,
         10.27721097],
        [10.70986348, 10.61115424, 10.72891639, 10.69941464, 10.65364626,
         10.5741473 , 10.6704777 , 10.69511892, 10.71843447, 10.65090304,
         10.68685676, 10.72283083, 10.70876001, 10.65174386, 10.70695523,
         10.66564337],
        [10.56123184, 10.50778039, 10.60244286, 10.58720012, 10.54450346,
         10.47201355, 10.56325367, 10.59603936, 10.65711021, 10.57575678,
         10.59214713, 10.59481746, 10.59732884, 10.55854006, 10.58222344,
         10.55768904],
        [10.57428076, 10.49212782, 10.59790392, 10.60766985, 10.55319365,
         10.4642703 , 10.55308972, 10.59291063, 10.62138192, 10.57058502,
         10.55933806, 10.60781059, 10.59397394, 10.55375128, 10.59204041,
         10.57056314],
        [10.48805093, 10.4176572 , 10.52038096, 10.5428831 , 10.47088488,
         10.39638998, 10.49679084, 10.5133629 , 10.53041913, 10.48908101,
         10.50113093, 10.55463364, 10.52779566, 10.46591271, 10.51793273,
         10.49928851],
        [10.24338379, 10.17993054, 10.26799211, 10.28229619, 10.22128444,
         10.13470823, 10.23457391, 10.27318482, 10.28994421, 10.25100331,
         10.26258595, 10.28513614, 10.27024617, 10.252992  , 10.26689577,
         10.23842281],
        [10.45152496, 10.36341916, 10.49516658, 10.48024242, 10.43163622,
         10.35199963, 10.44215327, 10.47784205, 10.49515871, 10.43843755,
         10.44411932, 10.48682839, 10.44598988, 10.44648184, 10.44601945,
         10.44295697],
        [10.32504479, 10.24457334, 10.36994087, 10.36043347, 10.30678839,
         10.23681638, 10.31946081, 10.3588994 , 10.38502755, 10.32888352,
         10.33854543, 10.38329386, 10.35826118, 10.31738501, 10.32650686,
         10.33151626],
        [10.1443761 , 10.06724062, 10.17602475, 10.18434679, 10.11234477,
         10.0425762 , 10.11998049, 10.14896651, 10.1769783 , 10.12479375,
         10.14378042, 10.17054777, 10.15815906, 10.10458442, 10.13600602,
         10.12696515],
        [10.37225671, 10.30256564, 10.40958039, 10.40482748, 10.3633177 ,
         10.28920187, 10.37743175, 10.39641293, 10.43967367, 10.36176788,
         10.36609463, 10.42552964, 10.40249723, 10.35908139, 10.39509197,
         10.35942249],
        [10.41746581, 10.36699074, 10.47203904, 10.44736306, 10.41805383,
         10.31069342, 10.41064647, 10.44902674, 10.45933459, 10.41814915,
         10.4304975 , 10.46524182, 10.45730972, 10.41231003, 10.43005007,
         10.41496674],
        [10.25534711, 10.18003937, 10.27819626, 10.28295387, 10.23222314,
         10.14151963, 10.24897966, 10.25448252, 10.27918432, 10.25268806,
         10.24857274, 10.28328422, 10.27043252, 10.22480706, 10.26861103,
         10.23210519],
        [10.58508786, 10.54476849, 10.62332479, 10.59583887, 10.56427285,
         10.48492531, 10.58964701, 10.60772844, 10.62519675, 10.59667551,
         10.59916232, 10.61182219, 10.6162561 , 10.56366622, 10.6119429 ,
         10.57776468]]),
b2 = ([[21.37161255],
        [21.33336309],
        [21.12979285],
        [20.87759066],
        [21.63231296],
        [21.42203589],
        [21.41536968],
        [21.27134069],
        [20.77416945],
        [21.17340388],
        [20.94476057],
        [20.54476777],
        [21.03540171],
        [21.12878295],
        [20.77357086],
        [21.45266035]]),
W3 = ([[78.20651974, 77.8225572 , 77.91205274, 77.43764734, 77.70046546,
         77.81093269, 78.13544123, 77.90719703, 78.36786193, 77.84772581,
         77.81804302, 78.60261366, 77.57251491, 77.88159996, 77.13746039,
         77.81676106]]),
b3 = ([[91.54653545]])


parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2,
                  "W3": W3,
                  "b3": b3}

In [18]:
parameters

{'W1': ([[0.1005317, 0.22764016, 0.30283889, 0.41307084, -0.00878571],
   [0.10726795, 0.25702785, 0.34551263, 0.42787668, 0.00089543],
   [0.14617458, 0.32950514, 0.43602154, 0.52256502, 0.01736305],
   [0.11533403, 0.26414214, 0.38688043, 0.45229581, 0.01045548],
   [0.20062603, 0.45484786, 0.65046201, 0.78392557, 0.01454719],
   [0.15400612, 0.33459909, 0.4722262, 0.5788094, 0.01185078],
   [0.18565756, 0.4327009, 0.55887736, 0.71523139, 0.01976579],
   [0.16175869, 0.32835734, 0.45076296, 0.56240652, 0.01804493],
   [0.11018652, 0.2546402, 0.33221024, 0.44669934, 0.02419948],
   [0.14727005, 0.33440278, 0.46662971, 0.5628373, 0.01374376],
   [0.14364158, 0.28786791, 0.41031109, 0.50644076, 0.01572308],
   [0.10829913, 0.20230712, 0.30114344, 0.36487727, -0.01019915],
   [0.13168729, 0.29487298, 0.42008656, 0.5183047, -0.00856066],
   [0.18271912, 0.3907151, 0.54996245, 0.69632152, 0.02285575],
   [0.07096658, 0.17716009, 0.23590965, 0.29426549, -0.0042446],
   [0.05748074, 0.06487184, 0.12852868, 0.16542658, -0.01653239]],),
 'b1': ([[0.47823922],
   [0.52823491],
   [0.64305632],
   [0.55396629],
   [0.95647949],
   [0.71445121],
   [0.86057077],
   [0.67774723],
   [0.51768132],
   [0.6881468],
   [0.61119131],
   [0.43713264],
   [0.62071621],
   [0.8328784],
   [0.35382257],
   [0.19106971]],),
 'W2': ([[10.54688957,
    10.47303148,
    10.59026428,
    10.58699344,
    10.51445713,
    10.42621253,
    10.54952942,
    10.57823338,
    10.58692647,
    10.54623335,
    10.55588064,
    10.59507172,
    10.57080311,
    10.53995594,
    10.54373333,
    10.55177346],
   [10.53364139,
    10.45290026,
    10.57477256,
    10.5325564,
    10.51111239,
    10.42503485,
    10.50594697,
    10.551563,
    10.56953056,
    10.5494587,
    10.55136733,
    10.57487553,
    10.54275607,
    10.5014423,
    10.53879663,
    10.51707389],
   [10.42048072,
    10.34943957,
    10.45964123,
    10.44988934,
    10.39252721,
    10.31259004,
    10.44201389,
    10.43206711,
    10.4615516,
    10.42774783,
    10.42950789,
    10.47384266,
    10.45710055,
    10.41943034,
    10.44885552,
    10.41237765],
   [10.31588155,
    10.21422961,
    10.33636146,
    10.32529084,
    10.26482057,
    10.20442527,
    10.29064749,
    10.33202999,
    10.33200289,
    10.30742725,
    10.31310781,
    10.34593631,
    10.31044794,
    10.28024383,
    10.30149166,
    10.27721097],
   [10.70986348,
    10.61115424,
    10.72891639,
    10.69941464,
    10.65364626,
    10.5741473,
    10.6704777,
    10.69511892,
    10.71843447,
    10.65090304,
    10.68685676,
    10.72283083,
    10.70876001,
    10.65174386,
    10.70695523,
    10.66564337],
   [10.56123184,
    10.50778039,
    10.60244286,
    10.58720012,
    10.54450346,
    10.47201355,
    10.56325367,
    10.59603936,
    10.65711021,
    10.57575678,
    10.59214713,
    10.59481746,
    10.59732884,
    10.55854006,
    10.58222344,
    10.55768904],
   [10.57428076,
    10.49212782,
    10.59790392,
    10.60766985,
    10.55319365,
    10.4642703,
    10.55308972,
    10.59291063,
    10.62138192,
    10.57058502,
    10.55933806,
    10.60781059,
    10.59397394,
    10.55375128,
    10.59204041,
    10.57056314],
   [10.48805093,
    10.4176572,
    10.52038096,
    10.5428831,
    10.47088488,
    10.39638998,
    10.49679084,
    10.5133629,
    10.53041913,
    10.48908101,
    10.50113093,
    10.55463364,
    10.52779566,
    10.46591271,
    10.51793273,
    10.49928851],
   [10.24338379,
    10.17993054,
    10.26799211,
    10.28229619,
    10.22128444,
    10.13470823,
    10.23457391,
    10.27318482,
    10.28994421,
    10.25100331,
    10.26258595,
    10.28513614,
    10.27024617,
    10.252992,
    10.26689577,
    10.23842281],
   [10.45152496,
    10.36341916,
    10.49516658,
    10.48024242,
    10.43163622,
    10.35199963,
    10.44215327,
    10.47784205,
    10.49515871,
    10.43843755,
    10.44411932,
    10.48682839,
    10.44598988,
    10.44648184,
    10.44601945,
    10.44295697],
   [10.32504479,
    10.24457334,
    10.36994087,
    10.36043347,
    10.30678839,
    10.23681638,
    10.31946081,
    10.3588994,
    10.38502755,
    10.32888352,
    10.33854543,
    10.38329386,
    10.35826118,
    10.31738501,
    10.32650686,
    10.33151626],
   [10.1443761,
    10.06724062,
    10.17602475,
    10.18434679,
    10.11234477,
    10.0425762,
    10.11998049,
    10.14896651,
    10.1769783,
    10.12479375,
    10.14378042,
    10.17054777,
    10.15815906,
    10.10458442,
    10.13600602,
    10.12696515],
   [10.37225671,
    10.30256564,
    10.40958039,
    10.40482748,
    10.3633177,
    10.28920187,
    10.37743175,
    10.39641293,
    10.43967367,
    10.36176788,
    10.36609463,
    10.42552964,
    10.40249723,
    10.35908139,
    10.39509197,
    10.35942249],
   [10.41746581,
    10.36699074,
    10.47203904,
    10.44736306,
    10.41805383,
    10.31069342,
    10.41064647,
    10.44902674,
    10.45933459,
    10.41814915,
    10.4304975,
    10.46524182,
    10.45730972,
    10.41231003,
    10.43005007,
    10.41496674],
   [10.25534711,
    10.18003937,
    10.27819626,
    10.28295387,
    10.23222314,
    10.14151963,
    10.24897966,
    10.25448252,
    10.27918432,
    10.25268806,
    10.24857274,
    10.28328422,
    10.27043252,
    10.22480706,
    10.26861103,
    10.23210519],
   [10.58508786,
    10.54476849,
    10.62332479,
    10.59583887,
    10.56427285,
    10.48492531,
    10.58964701,
    10.60772844,
    10.62519675,
    10.59667551,
    10.59916232,
    10.61182219,
    10.6162561,
    10.56366622,
    10.6119429,
    10.57776468]],),
 'b2': ([[21.37161255],
   [21.33336309],
   [21.12979285],
   [20.87759066],
   [21.63231296],
   [21.42203589],
   [21.41536968],
   [21.27134069],
   [20.77416945],
   [21.17340388],
   [20.94476057],
   [20.54476777],
   [21.03540171],
   [21.12878295],
   [20.77357086],
   [21.45266035]],),
 'W3': ([[78.20651974,
    77.8225572,
    77.91205274,
    77.43764734,
    77.70046546,
    77.81093269,
    78.13544123,
    77.90719703,
    78.36786193,
    77.84772581,
    77.81804302,
    78.60261366,
    77.57251491,
    77.88159996,
    77.13746039,
    77.81676106]],),
 'b3': [[91.54653545]]}

### TAKING INPUT FROM THE USER

In [19]:
prediction_df = pd.read_excel('Book2.xlsx')
prediction_df

    state_code                state_name population
0            1                    Alaska     1.2863
1            2                   Alabama    96.9221
2            3                  Arkansas     58.403
3            4            American Samoa        716
4            5                   Arizona    64.9549
5            6                California    256.373
6            7                  Colorado    56.4012
7            8               Connecticut     735.87
8            9      District Of Columbia      11535
9           10                  Delaware    504.307
10          11                   Florida    410.126
11          12                   Georgia    186.673
12          13                      Guam        809
13          14                    Hawaii    219.942
14          15                      Iowa    56.9284
15          16                     Idaho     22.097
16          17                  Illinois    228.025
17          18                   Indiana    188.281
18          19                    Kansas    35.5968
19          20                  Kentucky    113.957
20          21                 Louisiana    107.517
21          22             Massachusetts    894.436
22          23                  Maryland    626.673
23          24                     Maine    43.6336
24          25                  Michigan    177.665
25          26                 Minnesota    71.5922
26          27                  Missouri    89.7453
27          28  Northern Mariana Islands       324
28          29               Mississippi    63.7056
29          30                   Montana     7.4668
30          31            North Carolina    218.271
31          32              North Dakota    11.0393
32          33                  Nebraska    25.4161
33          34             New Hampshire    153.161
34          35                New Jersey     1215.2
35          36                New Mexico     17.285
36          37                    Nevada    28.5993
37          38                  New York    412.522
38          39                      Ohio    287.504
39          40                  Oklahoma    57.6546
40          41                    Oregon    44.8086
41          42              Pennsylvania    286.545
42          43                     Palau      876.6
43          44              Rhode Island    1021.43
44          45            South Carolina    173.318
45          46              South Dakota    11.9116
46          47                 Tennessee    167.275
47          48                     Texas     112.82
48          49                      Utah     39.943
49          50                  Virginia     218.44
50          51            Virgin Islands       773
51          52                   Vermont    68.1416
52          53                Washington    117.327
53          54                 Wisconsin     108.05
54          55             West Virginia    73.9691
55          56                   Wyoming       5.84

In [20]:
def Date_Code(year,month,day):
    import datetime
    date = datetime.date(2020, 12, 6)
    date1 = datetime.date(year,month,day)
    date_code = (date - date1)
    dayss = date_code.days
    print ('Date_code is:'  ,dayss)
    return dayss

In [21]:
year = int(input('Enter a year: '))
month = int(input('Enter a month: '))
day = int(input('Enter a day: '))
d = Date_Code(year,month,day)
d = d/X['Date_Code'].max()
d

Enter a year: 2020
Enter a month: 12
Enter a day: 12
Date_code is: -6

-0.022727272727272728

In [22]:
t = float(input('Enter value of Temperature: '))
t = t/X['Temperatures'].max()
t

Enter value of Temperature: 6

0.07246376811594203

In [23]:
hum = float(input('Enter value of Humidity: '))
hum = hum/X['Humidity'].max()
hum

Enter value of Humidity: 85

1.0625

In [24]:
s = float(input('Enter state Code: '))
s = s/X['States_Code'].max()
s

Enter state Code: 5

0.08928571428571429

In [25]:
p = float(input('Enter population Density: '))
p = p/X['Population_Density'].max()
p

Enter population Density: 650

0.05635023840485479

In [26]:
x_a = np.array([d,s,t,hum,p])
x_a

array([-0.02272727,  0.08928571,  0.07246377,  1.0625    ,  0.05635024])

In [27]:
def sigmoid(z):   #Defining Sigmoid funcion
        return 1.0/(1.0+np.exp(-z))

### PREDICTION CODE

In [28]:
def prediction(train_x, parameters):
    # train_x = input data of size (n_x, m)
    # Retrieve each parameter from the dictionary "parameters"
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    W3 = parameters["W3"]
    b3 = parameters["b3"]
    
    
    
    Z1 = np.dot(W1,train_x) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2,A1) + b2
    A2 = sigmoid(Z2)
    Z3=  np.dot(W3,A2) + b3
    A3=  Z3
    
   # assert(A3.shape == (1, train_x.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2,
             "Z3": Z3,
             "A3": A3
            }
    
    return A3, cache

In [29]:
y_hatt, cache = prediction(x_a, parameters)

In [31]:
print ("The Estimated count of Covid Cases is:   " , y_hatt.mean())

The Estimated count of Covid Cases is:    1337.5239296200002

### ERROR FROM ACTUAL CASES (IF AVAILABLE)

In [ ]:
### INPUT ACTUAL CASES IF AVAILABLE
actual_y = float(input('Enter value of Actual Cases: '))
actual_y

In [ ]:
### ERROR ON ACTUAL CASES vs PREDICTED CASES
def RMSE(y_hatt, actual_y):
    return np.sqrt((y_hatt - actual_y) ** 2).mean()
rmse_val = RMSE(np.array(y_hatt), np.array(actual_y))
print(f" Rms error is:  {rmse_val}")

In [ ]:
def MSE(y_hatt, actual_y):
    return (1/len(x_a))*np.sum((y_hatt - actual_y) ** 2)
mse_val = MSE(np.array(y_hatt), np.array(actual_y))
print(f" Mean Square Error is:  {mse_val}")